# Need superuser level
sudo: required
# Request to travis docker cli ready to go 
services:
  - docker

# Create a test container into ./client context ( last field ) 
before_install:
  # Decrypt the service-account.json file 
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  # Install the Google cloud SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Install and Update kubernetes inside travis environment
  - gcloud components update kubectl
  # Activate service account to access to google cloud
  - gcloud auth activate-service-account --key-file service-account.json




  - docker build -t ccazin/react-test -f ./client/Dockerfile.dev ./client

# The script has to return 0 to validate test 
script:
  - docker run ccazin/react-test npm run test -- --coverage

after_success:
  - docker build -t ccazin/multi-client ./client
  - docker build -t ccazin/multi-nginx ./nginx
  - docker build -t ccazin/multi-server ./server
  - docker build -t ccazin/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push ccazin/multi-client
  - docker push ccazin/multi-nginx
  - docker push ccazin/multi-server
  - docker push ccazin/multi-worker

  # Deployment on AWS
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"  
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-457357339164"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

